spring:
  application:
    name: e1
server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka,http://localhost:8763/eureka
#    fetch-registry: false
#    register-with-eureka: false