spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
server:
  port: 8085
zuul:
  routes:
    api-admin:
      path: /api/admin/**
      # serviceId: service-admin
      url: http://pkusoft.net/
    api-study:
      path: /api/study/**
      serviceId: study-consume
logging:
  level:
    com.netflix: info
hystrix:
  metrics:
    enabled: true
